# Important Notes:
# Every field you add must be added to buildSrc/src/main/groovy/multiloader-common.gradle expandProps map.

# Project
version=0.1.0
group=io.github.fishstiz
java_version=21

# Common
minecraft_version=1.21.4
mod_name=Packed Packs Lite
mod_author=fishstiz
mod_id=packed_packs_lite
license=MIT
credits=
description=Catalogs lists on select screens.
sources=https://github.com/fishstiz/packed_packs_lite
issues=https://github.com/fishstiz/packed_packs_lite/issues

# Common
mdg_version=2.0.107
neo_form_version=1.21.1-20240808.144430
parchment_minecraft=1.21.1
parchment_version=2024.11.17
minecraft_version_range=[1.21.1, 1.22)
mccursor_version=3.11.1+1.21.1

# Fabric
loom_version=1.11-SNAPSHOT
fabric_version=0.116.7+1.21.1
fabric_loader_version=0.17.3

# NeoForge
neoforge_version=21.1.213
neoforge_loader_version_range=[4,)
mccursor_dev_version=3.11.1-dev.1+1.21.1

# Gradle
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false
